[project]
name = "stego-crypt-utils"
version = "0.1.0"
description = "Steganography/Cryptography Utilities"
readme = "README.md"
authors = [
    { name = "IronGreninja", email = "92992745+IronGreninja@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "pillow>=12.3.0",
    "typer>=0.27.2",
]

[project.scripts]
stego-cli = "stego_cli:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["stego_cli"]
